function Get-DefaultLocalEvent {
  [CmdletBinding()]
  param
  (
    [Parameter(
      Position = 1,
      Mandatory = $True,
      ValueFromPipeline = $False,
      ValueFromPipelineByPropertyName = $False,
      HelpMessage='Local Event generated by detector')]
    [string]$DetectorName,

    [Parameter(
      Position = 2,
      Mandatory = $True,
      ValueFromPipeline = $False,
      ValueFromPipelineByPropertyName = $False,
      HelpMessage='Local Event generated by detector')]
    [int]$DetectorId
)
  $LocalEvent = @{
    detectorID = $DetectorId;
    status = "grey";
    eventShort = "This is the defult event for $detectorName";
    contentType = "Text";
    descriptionDetails = "This is the defult event for $detectorName on $env:COMPUTERNAME by $env:USERNAME at $(get-date -format 'yyyy-MM-dd HH:mm')"
  }
  Return $LocalEvent
}
