function Test-IfNewEvent {
  [CmdletBinding()]
  param
  (
    [Parameter(
      Position = 1,
      Mandatory = $True,
      ValueFromPipeline = $False,
      ValueFromPipelineByPropertyName = $False,
      HelpMessage='Local Event generated by detector')]
    [Object]$LocalEvent,

    [Parameter(
      Position = 2,
      Mandatory = $False,
      ValueFromPipeline = $False,
      ValueFromPipelineByPropertyName = $False,
      HelpMessage='Test details')]
    [switch]$details
)
  $CurrentEvent = Get-ODBCData -query "SELECT * FROM $eventTable WHERE detectorId = $($localEvent.detectorid) ORDER BY eventId DESC LIMIT 1"
  if ($details)
  {
    $eventdetails = (Get-ODBCData -query "SELECT descriptiondetails FROM $eventDescriptionTable WHERE eventId = $($CurrentEvent.eventid)").descriptiondetails
    if (Compare-Object ($localEvent.descriptionDetails | ConvertFrom-Json) ($eventdetails | ConvertFrom-Json))
    {
      return $true
    }
    else {return $false}
  }
  elseif (($LocalEvent.status -like $CurrentEvent.status) -and ($LocalEvent.eventShort -like $CurrentEvent.eventShort) -and ([string]::IsNullOrEmpty($CurrentEvent.snoozets)))
  {
    Return $false
  }
  else {Return $true}
}
