function Test-IfSnoozed {
  [CmdletBinding()]
  param
  (
    [Parameter(
      Position = 1,
      Mandatory = $True,
      ValueFromPipeline = $False,
      ValueFromPipelineByPropertyName = $False,
      HelpMessage='Local Event generated by detector')]
    [int]$DetectorId
)
  $CurrentEvent = Get-ODBCData -query "SELECT * FROM $eventTable WHERE detectorId = $detectorId ORDER BY eventId DESC LIMIT 1"
  $snoozeTime = Get-ODBCData -query "SELECT snoozeTime FROM $inventoryTable WHERE detectorId = $detectorId" | select -ExpandProperty snoozeTime
  If ([string]::IsNullOrEmpty($CurrentEvent.snoozeTS))
  {
    Return $False
  }
  Else {Return ($CurrentEvent.snoozets.AddSeconds($snoozeTime) -gt (get-date))}
}
