function Write-HeartBeat {
  [CmdletBinding()]
  param
  (
    [Parameter(
      Position = 1,
      Mandatory = $True,
      ValueFromPipeline = $False,
      ValueFromPipelineByPropertyName = $False,
      HelpMessage='Local Event generated by detector')]
    [int]$detectorId
)
  Set-ODBCData -query "UPDATE $inventoryTable SET heartBeatTS = now() WHERE detectorId = $detectorId"
}
